// compiler/scheme_entry.s
// L00: hand-written Darwin/arm64 _scheme_entry. Not generated by Python,
// Chez, Guile, or any other HLL. Makefile and shell scripts only assemble,
// link, run, and compare expected output.
//
// Returns bare untagged 42 in x0. Does not apply FX_SHIFT.
// Does not issue a system call; I/O and mmap belong in runtime.s.
//
// Prologue choice (locked for this layer): save/restore only x29 and x30.
// Heap base arrives in x0 and size in x1; this layer does not copy them
// into HP (x19). L12 will add callee-saved x19/x20 without changing the
// two-argument entry.

        .text
        .globl  _scheme_entry
        .p2align 2
_scheme_entry:
        stp     x29, x30, [sp, #-16]!
        mov     x29, sp
        mov     x0, #42
        ldp     x29, x30, [sp], #16
        ret
